### Site metadata

title: From Lester Levenson
description: Teachings from this Self-realized master

### Build settings

url: https://from-lester.github.io
baseurl: /
incremental: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - docs/
  - LICENSE
  - Makefile
  - README.md

### Theme settings
#plugin: jekyll-include-cache
#theme: minimal-mistakes-jekyll
theme: just-the-docs


heading_anchors: true
nav_enabled: true

aux_links:
  "View source": "https://github.com/from-lester/from-lester.github.io"
